Sprint 4
DOXOPOKC/middle.messenger.praktikum.yandex pull request #4
Opened 2021-07-29 14:04 UTC by DOXOPOKC

2021-07-29 17:19 UTC, nickchamel requested changes
Привет. По заданиям спринта все хорошо. Но есть критичные моменты по работе, которые необходимо поправить:
1.

При изменении профиля, нужно записать в форму текущие данные юзера. Сейчас при изменении одного филда, все остальные отправляются как пустые строки.
2. В профиле и апдейте профиля не грузится аватар.
3. Кол-во новых сообщений (иконка на чате) либо нужно сделать рабочим, либо убрать.
![image](https://user-images.githubusercontent.com/28347933/127535261-755e27ef-2640-4463-ad67-b0ad5ca2b728.png)
4. Кнопка выхода не работает.
![image](https://user-images.githubusercontent.com/28347933/127535994-4cd5828b-4b33-45a7-9b45-14e70659cc35.png)

Не критично (по желанию):
При добавлении сообщения в чат и при переключении между чатами, лучше бы проматывать скролл в конец, чтобы было видно последнее сообщение.

2021-07-29 17:19 UTC, nickchamel commented on package.json
> +    "@babel/cli": "^7.14.8",
версии библиотек можно зафиксировать, чтобы не возникло проблем в будущем

2021-08-01 06:08 UTC, nickchamel commented
Привет. Сейчас на апдейте профиля нередактируемая форма с данными юзера - и только после клика на аватаре ее можно редактировать, это ведь не совсем очевидно, согласен? :) она должна быть редактируема и в ней уже должны быть данные юзера вбиты, чтобы нам все не вбивать вручную, если мы хотим например просто имя поменять.
После перехода со страницы чатов на профиль все ок, а если профиль обновить то данные дефолтные подставляются,  хотя запрос на юзера у тебя есть. Плюс в любом из вариантов сверху всегда имя Иван.
Давай последние штрихи и готово!

2021-08-01 07:35 UTC, DOXOPOKC commented
Привет, надеюсь теперь все поправил) Можешь дать пару советов по архитектуре моего проекта? Наприсер, что стоит изменить и как. Сейчас это совершенно негибкая и неоптимизированная система с больши кол-вом багов. Как мне кажется стоит переписать всю логику работы с классом блок и сам этот класс, возможно добавить свой virtualDom, для этого нужно будет убрать pug и генерировать из темплейта обьекты { type, props, children }, по аналогии с реактом, или можно как-то проще все сделать?

2021-08-01 12:50 UTC, nickchamel commented
> Привет, надеюсь теперь все поправил) Можешь дать пару советов по архитектуре моего проекта? Наприсер, что стоит изменить и как. Сейчас это совершенно негибкая и неоптимизированная система с больши кол-вом багов. Как мне кажется стоит переписать всю логику работы с классом блок и сам этот класс, возможно добавить свой virtualDom, для этого нужно будет убрать pug и генерировать из темплейта обьекты { type, props, children }, по аналогии с реактом, или можно как-то проще все сделать?

В целом все ок, но например можно вынести создание чилдренов в `Block`, будет меньше ручной работы.
Плюс апдейт чилдренов делать тоже через блок. Например, заместо этого
```
const user = await UserController.getUser(true);

if (user) {
	fields.forEach((field => {
		field.setProps({value: user[field.props.name]});
	}));

	form.setProps({fields});
	this.setProps({avatar: user.avatar, title: user.first_name, form});
}
```
можно сделать только
```
this.setProps({ user });
```
компонент обновится, а в реализации `Block` в этот момент (didUpdate), можно пробежаться по чилдренам и сделать setProps у них, и тогда за счет рекурсии (парент-чилдрен) все будет рендериться и обновляться.

Кстати
`const user = await UserController.getUser(true)` может завершиться ошибкой? Значит должно быть обернуто в try/catch.

Ну а по поводу виртуал дом... ну можно конечно, так то можно много чего сделать) Можешь поиграться. Но даже с виртуал дом все равно будут такие же моменты... у тебя основной путь улучшения - реализовать логику парент-чилдрен в `Block`.

И еще момент - если обновить например имя, у тебя редиректит на /profile, а там имя старое) Тоже можешь поправить.
В целом сейчас вроде работает, работу принимаю. Успехов в след. модуле!

2021-08-02 04:34 UTC, merged